### create category - post method
POST http://localhost:8000/api/lead
Content-Type: application/json

{
   "amount":2000,
   "price":40
}

### get lead list - get method
GET http://localhost:8000/api/lead
Content-Type: application/json

### get category list - get method
GET http://localhost:8000/api/category
Content-Type: application/json

### add user - post method
POST http://localhost:8000/api/user/addUser
Content-Type: application/json

{
   "name":"mansi",
   "email":"mansi@gmail.com",
   "number":"9265547512",
   "website":"https://github.com/Mansi231/PYTHON-SQUARE",
   "leadAmount":200
}

### delete payment intent - post method
POST http://localhost:8000/api/user/deletePaymentIntent
Content-Type: application/json

{
   "payment_intent_id":"pi_3OjE7lSDRTuxnZ6y1Ec1Wwcr"
}

### delete payment intent - post method
POST http://localhost:8000/api/pay
Content-Type: application/json

{
   "payment_id":"pi_3OjE5nSDRTuxnZ6y0ByX6Vhh",
   "clientSecret":"pi_3OjE5nSDRTuxnZ6y0ByX6Vhh_secret_HpRnRaJFBgDIyun4wMWf8jLwo"
}
